/**
 * FESim 룰 엔진 — 계약: (국면, 행동, 난수소스) → 다음 국면.
 * 순수 함수 라이브러리: 입력을 변이하지 않고, 난수는 항상 주입받는다
 * (기록 재생 = 리플레이 · 실굴림 = 샌드박스 · 열거 = 솔버가 같은 코어를 공유).
 */
export {
  BAD_STATE,
  canBreak,
  canChainGuard,
  canDance,
  chainGuardFor,
  createReducer,
  canterPower,
  hasChainGuardSkill,
  effectiveSkills,
  effectiveWeapons,
  hasBadState,
  itemTargets,
  moveBase,
  moveBudget,
  moveBudgetOn,
  movePower,
  movePredicates,
  allianceOf,
  terrainBonusAt,
  makeCostAt,
  destroyTargets,
  overlayAt,
  structureAt,
  staffHealAmount,
  staffHitRate,
  toCombatant,
  warpDestinations,
  weaponAdvantage,
  type Advantage,
  type BattleAction,
  type BattleEvent,
  type BattleMap,
  type MapInteraction,
  type TerrainCell,
  type OverlaySpot,
  type StructureState,
  type BattleWeapon,
  type Difficulty,
  type GameState,
  type RandomSource,
  type StrikeKind,
  type SupportEffects,
  type UnitState,
} from "./battle.js";

export { carryover } from "./campaign.js";

export {
  createReplayer,
  recordingSource,
  sequenceSource,
  toAddress,
  toCursor,
  ReplayDesyncError,
  RULE_VERSION,
  type PhaseName,
  type PhaseSpan,
  type RecordingSource,
  type Reduce,
  type StepAddress,
  type Timeline,
  type VerifyMismatch,
  type VerifyResult,
} from "./replay.js";

export {
  attackRange,
  movementPath,
  movementRange,
  IMPASSABLE,
  MOVE_TYPES,
  type MoveQuery,
  type MoveType,
  type ReachableTile,
  type Tile,
} from "./range.js";
export { makeSkillModifier, staticEnhances, type SkillRow } from "./skills.js";
export type { ConsumableItem, EngageArt, EngageState, StaffItem } from "@fesim/shared";
export {
  deriveStats,
  grownLevels,
  STAT_KEYS,
  type DeriveStatsInput,
  type StatBlock,
  type StatKey,
} from "./stats.js";
export { parseFormula, type FormulaNode, type BinaryOp } from "./formula/parser.js";
export { evaluateFormula, type FormulaEnv, type FormulaValue } from "./formula/evaluate.js";
export { createCalculator, type Calculator } from "./formula/calculator.js";
export { hitThreshold10000, isHit, isProbability100 } from "./formula/probability.js";
export { createAi, emptyAiMemory, type Ai, type AiDecision, type AiMemory } from "./ai/index.js";
export {
  NONE,
  processing,
  slotsOf,
  type ActionResult,
  type OpcodeHandlers,
  type ProcessingInput,
  type ProcessingOutput,
  type SlotSource,
  type ThinkRuntime,
} from "./ai/interpreter.js";
export {
  MOVE_FLAG,
  attackTo,
  calcHealRodScore,
  eachEnemyUnit,
  guardTo,
  healMindTo,
  mindBreakDown,
  mindEscape,
  mindTorch,
  mindTreasure,
  isEscapePosition,
  moveAttackRange,
  moveBreakDown,
  moveEscape,
  mindVillage,
  moveHero,
  movePerson,
  movePosition,
  moveIdle,
  moveTo,
  interferenceRank,
  interferenceScore,
  rodHealTo,
  rodInterferenceTo,
  targetFilter,
  type HandlerContext,
} from "./ai/handlers.js";
export {
  aiIsRandom,
  betterAttack,
  compareBlow,
  rejectsLowKill,
  getAttackPosition,
  getAttackScore,
  moveImageOf,
  type AttackContext,
  type AttackEvaluation,
  type AttackPosition,
} from "./ai/attack.js";
export {
  AC,
  ACT,
  AI_ACTIVE,
  AI_CODE,
  AI_FLAG,
  AI_SLOT,
  AI_THINK,
  AI_VALUE,
  ATTACK_FLAG,
  BATTLE_RATE,
  battleRateOf,
  type AiCommand,
  type AiDeficit,
  type AiSlot,
  type AiSnapshot,
  type BattleRate,
} from "./ai/types.js";
export {
  AI_GUARD,
  battleScore,
  expectationScoreNormalize,
  killProbability,
  killScoreNormalize,
  simulateBattle,
  type BattleScoreInput,
  type Indication,
  type SimulationInput,
  type SimulationResult,
} from "./ai/score.js";
export {
  BLOW_SCORE,
  TID_HOLE,
  attackPositionScore,
  blowScoreAt,
  enumerateRing,
  healRodPositionScore,
  rangeMask,
  terrainScoreAt,
  type PositionScoreInput,
} from "./ai/position.js";
export {
  AI_PHASES,
  aiCanAct,
  aiPhaseQueue,
  aiPriorityKey,
  aiPriorityQueue,
  attackTierAllowed,
  slotGateOpen,
  type AiPhaseStep,
} from "./ai/order.js";
export {
  CAUSE_STRING_ARG,
  argsOf,
  attackAreaFrom,
  healAreaFrom,
  interferenceAreaFrom,
  parsePos,
  evaluateCause,
  movePowerOf,
  resolveValue,
  threatTiles,
  type CauseContext,
} from "./ai/cause.js";
export {
  aiHasFlag,
  aiHealCondition,
  bandMembers,
  moveLimitAllows,
  parseMoveLimit,
  rejectsPower0,
  type MoveLimitRect,
} from "./ai/unit.js";
export {
  combatEnv,
  forecastSide,
  type Combatant,
  type CombatantStats,
  type CombatantWeapon,
  type SideForecast,
} from "./formula/combat.js";
export {
  createRandom,
  INIT_SPIN,
  randomFromState,
  seedState,
  type Random,
  type RandomState,
} from "./random.js";
